module.exports = [
   { taunt: 1, message: "Yes." },
   { taunt: 2, message: "No." },
   { taunt: 3, message: "I need food!" },
   { taunt: 4, message: "I need wood!" },
   { taunt: 5, message: "I need coin!" },
   { taunt: 6, message: "Do you have extra reasources?" },
   { taunt: 7, message: "I have extra food" },
   { taunt: 8, message: "I have extra wood." },
   { taunt: 9, message: "I have extra coin." },
   { taunt: 10, message: "Meet here." },
   { taunt: 11, message: "Are you ready?" },
   { taunt: 12, message: "I need help!" },
   { taunt: 13, message: "Attack now!" },
   { taunt: 14, message: "Upgrade your trade route!" },
   { taunt: 15, message: "*Wololo*" },
   { taunt: 16, message: "I'm in your base, killin' your dudes." },
   { taunt: 17, message: "Check in your wallet; that's me on your dollar bill" },
   { taunt: 18, message: "I believe that, makes me your daddy." },
   { taunt: 19, message: "L-O-L, I am R-O-T-F-L!" },
   { taunt: 20, message: "Aren't you becoming quite the little problem?" },
   { taunt: 21, message: "*Laughter* {Ha-hahahahaha!} (the malicious sounding one)" },
   { taunt: 22, message: "This will give me cred, street cred!" },
   { taunt: 23, message: "Hey shut your pie hole." },
   { taunt: 24, message: "I'll take that trade." },
   { taunt: 25, message: "You sit on the computer all day, play! You know nothing of hard life!" },
   { taunt: 26, message: "REA-lly? Such a noob." },
   { taunt: 27, message: "Ask not for who the timer ticks; it ticks for the." },
   { taunt: 28, message: "*Laughter* {Hoi-hoi!} (the funny sounding one" },
   { taunt: 29, message: "Check in your pocket; the quarter is me too." },
   { taunt: 30, message: "Where is my mother?" },
   { taunt: 31, message: '*Trumpet "call for the attack" fanfare*' },
   { taunt: 32, message: "Believe it little boy!" },
   { taunt: 33, message: "Zing!" },
];
