# This is a basic workflow to deploy on a server

name: Deploy to Server

# Controls when the workflow will run
on:
   # Triggers the workflow on push or pull request events but only for the "main" branch
   push:
      branches: ["main"]
   pull_request:
      branches: ["main"]

   # Allows you to run this workflow manually from the Actions tab
   workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
   # This workflow contains a single job called "deploy"
   deploy:
      runs-on: Linux

      strategy:
         matrix:
            node-version: [20.18.0]

      steps:
         - uses: actions/checkout@v4

         - name: Use Node.js ${{ matrix.node-version }}
           uses: actions/setup-node@v4
           with:
              node-version: ${{ matrix.node-version }}

         - name: Installing NPM Packages
           run: npm install

         - name: Installing Server & Build Tools
           run: npm install typescript copyfiles

         - name: Installing PM2 Globally
           run: sudo -S <<< "${{ secrets.SUDO_PASSWORD }}" npm install -g pm2

         - name: Create .env file
           run: |
              touch .env
              echo TOKEN=${{secrets.TOKEN}} >> .env
              echo MONGO_URI=${{secrets.MONGO_URI}} >> .env

         - name: Installing NPM Packages
           run: npm install

         - name: Run the process
           run: pm2 start . --name ${{github.repository}}
